name: New mod request
description: Request a new mod here
labels: [newmod]
body:
  - type: textarea
    attributes:
      label: "What mod should be added in? (paste the link here, and make sure it's in github.)"
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: "Why **should** it be added?"
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: "Put the Title, The person who made it, Description, Image URL, URL (Info, Discord [Optional], Github [Optional], Download, Person who made it) in a format that's readable. (ex; Title: Creativity Archived)"
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: "Is it open source?"
      options:
        - Yes
        - No
    validations:
      required: true
  
  - type: dropdown
    attributes:
      label: "Does it mess with your system?"
      options:
        - Yes
        - No
    validations:
      required: true